// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import FormController from "./form_controller.js"
application.register("form", FormController)

import ModalController from "./modal_controller.js"
application.register("modal", ModalController)

document.addEventListener("keydown", (event) => {
    if (event.key === "Escape") {
        document.getElementById("popup-modal").classList.add("hidden")
    }
})